import os
import shutil
import subprocess
import uuid
from datetime import datetime
import requests
from core.config import *
from core.constants import *
from core.graphql import *


def _simulate() -> bool:
    """
    True whenever we should not touch real git or the real GitHub API:
    always in demo mode, and as a safety net in live mode if credentials
    are still missing for any reason.
    """
    return bool(DEMO_MODE) or not (GITHUB_TOKEN and GITHUB_OWNER and GITHUB_REPO)


def push_repairs_to_github(file_paths):
    branch = (
        "repair-"
        + datetime.now().strftime("%Y%m%d-%H%M%S")
        + "-"
        + uuid.uuid4().hex[:6]
    )
    filenames = []
    repair_dir = LOCAL_REPO
    repair_dir.mkdir(
        parents=True,
        exist_ok=True,
    )
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    for file_path in file_paths:
        source = Path(file_path).resolve()
        if not source.exists():
            raise FileNotFoundError(f"Repair script not found: {source}")
        destination = (repair_dir / f"{timestamp}_{source.name}").resolve()
        shutil.copy2(
            source,
            destination,
        )
        if not destination.exists():
            raise RuntimeError(f"Copy failed: {destination}")
        filenames.append(destination.name)

    if _simulate():
        print(
            "[JUDGE MODE] Skipping real git operations "
            "(DEMO_MODE=true or GitHub credentials missing)."
        )
        print(f"[JUDGE MODE] Repair script(s) copied to: {repair_dir}")
        return branch, filenames

    subprocess.run(
        ["git", "checkout", "main"],
        cwd=str(LOCAL_REPO),
        check=True,
    )
    subprocess.run(
        ["git", "pull", "origin", "main"],
        cwd=str(LOCAL_REPO),
        check=True,
    )
    subprocess.run(
        ["git", "checkout", "-b", branch],
        cwd=str(LOCAL_REPO),
        check=True,
    )
    subprocess.run(
        [
            "git",
            "add",
            "agents/",
            "core/",
            "demo/",
            "examples/",
        ],
        cwd=str(LOCAL_REPO),
        check=True,
    )
    subprocess.run(
        [
            "git",
            "commit",
            "-m",
            f"Ripple AI repair ({len(filenames)} generated repair scripts)",
        ],
        cwd=str(LOCAL_REPO),
        check=True,
    )
    if GITHUB_TOKEN and GITHUB_OWNER and GITHUB_REPO:
        authenticated_url = f"https://x-access-token:{GITHUB_TOKEN}@github.com/{GITHUB_OWNER}/{GITHUB_REPO}.git"
        subprocess.run(
            ["git", "remote", "set-url", "origin", authenticated_url],
            cwd=str(LOCAL_REPO),
            check=True,
        )
    subprocess.run(
        ["git", "push", "-u", "origin", branch],
        cwd=str(LOCAL_REPO),
        check=True,
    )
    subprocess.run(
        ["git", "checkout", "main"],
        cwd=str(LOCAL_REPO),
        check=True,
    )
    subprocess.run(
        ["git", "pull", "origin", "main"],
        cwd=str(LOCAL_REPO),
        check=True,
    )
    return branch, filenames


def create_pull_request(branch, dataset_name, gap_days, filenames):
    repair_list = "\n".join(f"- `{name}`" for name in filenames)

    if _simulate():
        os.makedirs("examples", exist_ok=True)
        pr_path = EXAMPLES_DIR / "pr_preview.md"
        repair_scripts_text = ""
        for name in filenames:
            script_path = LOCAL_REPO / name
            if script_path.exists():
                repair_scripts_text += f"\n### `{name}`\n```python\n{script_path.read_text(encoding='utf-8')}\n```\n"
        pr_path.write_text(
            f"""# Simulated GitHub Pull Request

> Generated by Ripple AI in JUDGE MODE — no real GitHub credentials were
> used and nothing was pushed. In a live run with GITHUB_TOKEN set, this
> branch would be pushed and a PR opened against {GITHUB_OWNER or "<owner>"}/{GITHUB_REPO or "<repo>"}.

**Branch:** `{branch}`
**Dataset:** {dataset_name}
**Freshness Gap:** {gap_days} day(s)

## Generated Repairs
{repair_list}
{repair_scripts_text}
""",
            encoding="utf-8",
        )
        pr_url = f"file://{pr_path}"
        print(f"[JUDGE MODE] Simulated PR preview written to {pr_path}")
        return pr_url

    url = f"https://api.github.com/repos/{GITHUB_OWNER}/{GITHUB_REPO}/pulls"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
    }
    payload = {
        "title": f"Repair freshness SLA - {dataset_name}",
        "head": branch,
        "base": "main",
        "body": f"""## Ripple AI Automated Repair
    ### Dataset
    {dataset_name}
    ### Freshness Gap
    {gap_days} day(s)
    ### Generated Repairs
    {repair_list}
    ### Root Cause
    Freshness SLA violation detected automatically.
    ### Verification
    Repair executed successfully.
    Freshness SLA revalidated after repair.
    ### Description
    Ripple AI:
    - Detected the SLA breach
    - Traced lineage in DataHub
    - Computed blast radius
    - Generated repair script(s) using an LLM
    - Executed repair
    - Verified freshness
    - Created this Pull Request automatically
    Please review before merging.
    """,
    }
    response = requests.post(
        url,
        headers=headers,
        json=payload,
    )
    data = response.json()
    if response.status_code not in (200, 201):
        console.print(data)
        return None
    pr_url = data["html_url"]
    console.print(f"[bold green]PULL REQUEST CREATED[/] {pr_url}")
    return pr_url
